<?php 
  $garage_attached = ($_GET["garage_type"] == "attached" ? "1" : "0");
  $garage_detached = ($_GET["garage_type"] == "detached" ? "1" : "0");
  $garage_none = ($_GET["garage_type"] == "none" ? "1" : "0");

  $Amystad = ($_GET["city"] == "Amystad" ? "1" : "0"); 
  $Brownport = ($_GET["city"] == "Brownport" ? "1" : "0"); 
  $Chadstad = ($_GET["city"] == "Chadstad" ? "1" : "0"); 
  $Clarkberg = ($_GET["city"] == "Clarkberg" ? "1" : "0"); 
  $Coletown = ($_GET["city"] == "Coletown" ? "1" : "0"); 
  $Davidfort = ($_GET["city"] == "Davidfort" ? "1" : "0"); 
  $Davidtown = ($_GET["city"] == "Davidtown" ? "1" : "0"); 
  $East_Amychester = ($_GET["city"] == "East_Amychester" ? "1" : "0"); 
  $East_Janiceville = ($_GET["city"] == "East_Janiceville" ? "1" : "0"); 
  $East_Justin = ($_GET["city"] == "East_Justin" ? "1" : "0"); 
  $East_Lucas = ($_GET["city"] == "East_Lucas" ? "1" : "0"); 
  $Fosterberg = ($_GET["city"] == "Fosterberg" ? "1" : "0"); 
  $Hallfort = ($_GET["city"] == "Hallfort" ? "1" : "0"); 
  $Jeffreyhaven = ($_GET["city"] == "Jeffreyhaven" ? "1" : "0"); 
  $Jenniferberg = ($_GET["city"] == "Jenniferberg" ? "1" : "0"); 
  $Joshuafurt = ($_GET["city"] == "Joshuafurt" ? "1" : "0"); 
  $Julieberg = ($_GET["city"] == "Julieberg" ? "1" : "0"); 
  $Justinport = ($_GET["city"] == "Justinport" ? "1" : "0"); 
  $Lake_Carolyn = ($_GET["city"] == "Lake_Carolyn" ? "1" : "0"); 
  $Lake_Christinaport = ($_GET["city"] == "Lake_Christinaport" ? "1" : "0"); 
  $Lake_Dariusborough = ($_GET["city"] == "Lake_Dariusborough" ? "1" : "0"); 
  $Lake_Jack = ($_GET["city"] == "Lake_Jack" ? "1" : "0"); 
  $Lake_Jennifer = ($_GET["city"] == "Lake_Jennifer" ? "1" : "0"); 
  $Leahview = ($_GET["city"] == "Leahview" ? "1" : "0"); 
  $Lewishaven = ($_GET["city"] == "Lewishaven" ? "1" : "0"); 
  $Martinezfort = ($_GET["city"] == "Martinezfort" ? "1" : "0"); 
  $Morrisport = ($_GET["city"] == "Morrisport" ? "1" : "0"); 
  $New_Michele = ($_GET["city"] == "New_Michele" ? "1" : "0"); 
  $New_Robinton = ($_GET["city"] == "New_Robinton" ? "1" : "0"); 
  $North_Erinville = ($_GET["city"] == "North_Erinville" ? "1" : "0"); 
  $Port_Adamtown = ($_GET["city"] == "Port_Adamtown" ? "1" : "0"); 
  $Port_Andrealand = ($_GET["city"] == "Port_Andrealand" ? "1" : "0"); 
  $Port_Daniel = ($_GET["city"] == "Port_Daniel" ? "1" : "0"); 
  $Port_Jonathanboroug = ($_GET["city"] == "Port_Jonathanboroug" ? "1" : "0"); 
  $Richardport = ($_GET["city"] == "Richardport" ? "1" : "0"); 
  $Rickytown = ($_GET["city"] == "Rickytown" ? "1" : "0"); 
  $Scottberg = ($_GET["city"] == "Scottberg" ? "1" : "0"); 
  $South_Anthony = ($_GET["city"] == "South_Anthony" ? "1" : "0"); 
  $South_Stevenfurt = ($_GET["city"] == "South_Stevenfurt" ? "1" : "0"); 
  $Toddshire = ($_GET["city"] == "Toddshire" ? "1" : "0"); 
  $Wendybury = ($_GET["city"] == "Wendybury" ? "1" : "0"); 
  $West_Ann = ($_GET["city"] == "West_Ann" ? "1" : "0"); 
  $West_Brittanyview = ($_GET["city"] == "West_Brittanyview" ? "1" : "0"); 
  $West_Gerald = ($_GET["city"] == "West_Gerald" ? "1" : "0"); 
  $West_Gregoryview = ($_GET["city"] == "West_Gregoryview" ? "1" : "0"); 
  $West_Lydia = ($_GET["city"] == "West_Lydia" ? "1" : "0"); 
  $West_Terrence = ($_GET["city"] == "West_Terrence" ? "1" : "0"); 

  $CMD_STRING = "python make_predictions_cli.py ";
  $CMD_STRING.= $_GET["year"]." ";
  $CMD_STRING.= $_GET["storeys"]." ";
  $CMD_STRING.= $_GET["bedrooms"]." ";
  $CMD_STRING.= $_GET["full_bathrooms"]." ";
  $CMD_STRING.= $_GET["half_bathrooms"]." ";
  $CMD_STRING.= $_GET["livable_sqft"]." ";
  $CMD_STRING.= $_GET["total_sqft"]." ";
  $CMD_STRING.= $_GET["garage_sqft"]." ";
  $CMD_STRING.= $_GET["carport_sqft"]." ";
  $CMD_STRING.= $_GET["has_fireplace"]." ";
  $CMD_STRING.= $_GET["has_pool"]." ";
  $CMD_STRING.= $_GET["has_central_heating"]." ";
  $CMD_STRING.= $_GET["has_central_cooling"]." ";
  $CMD_STRING.= $garage_attached." ";
  $CMD_STRING.= $garage_detached." ";
  $CMD_STRING.= $garage_none." ";
  $CMD_STRING.= $Amystad." ";
  $CMD_STRING.= $Brownport." ";
  $CMD_STRING.= $Chadstad." ";
  $CMD_STRING.= $Clarkberg." ";
  $CMD_STRING.= $Coletown." ";
  $CMD_STRING.= $Davidfort." ";
  $CMD_STRING.= $Davidtown." ";
  $CMD_STRING.= $East_Amychester." ";
  $CMD_STRING.= $East_Janiceville." ";
  $CMD_STRING.= $East_Justin." ";
  $CMD_STRING.= $East_Lucas." ";
  $CMD_STRING.= $Fosterberg." ";
  $CMD_STRING.= $Hallfort." ";
  $CMD_STRING.= $Jeffreyhaven." ";
  $CMD_STRING.= $Jenniferberg." ";
  $CMD_STRING.= $Joshuafurt." ";
  $CMD_STRING.= $Julieberg." ";
  $CMD_STRING.= $Justinport." ";
  $CMD_STRING.= $Lake_Carolyn." ";
  $CMD_STRING.= $Lake_Christinaport." ";
  $CMD_STRING.= $Lake_Dariusborough." ";
  $CMD_STRING.= $Lake_Jack." ";
  $CMD_STRING.= $Lake_Jennifer." ";
  $CMD_STRING.= $Leahview." ";
  $CMD_STRING.= $Lewishaven." ";
  $CMD_STRING.= $Martinezfort." ";
  $CMD_STRING.= $Morrisport." ";
  $CMD_STRING.= $New_Michele." ";
  $CMD_STRING.= $New_Robinton." ";
  $CMD_STRING.= $North_Erinville." ";
  $CMD_STRING.= $Port_Adamtown." ";
  $CMD_STRING.= $Port_Andrealand." ";
  $CMD_STRING.= $Port_Daniel." ";
  $CMD_STRING.= $Port_Jonathanboroug." ";
  $CMD_STRING.= $Richardport." ";
  $CMD_STRING.= $Rickytown." ";
  $CMD_STRING.= $Scottberg." ";
  $CMD_STRING.= $South_Anthony." ";
  $CMD_STRING.= $South_Stevenfurt." ";
  $CMD_STRING.= $Toddshire." ";
  $CMD_STRING.= $Wendybury." ";
  $CMD_STRING.= $West_Ann." ";
  $CMD_STRING.= $West_Brittanyview." ";
  $CMD_STRING.= $West_Gerald." ";
  $CMD_STRING.= $West_Gregoryview." ";
  $CMD_STRING.= $West_Lydia." ";
  $CMD_STRING.= $West_Terrence." ";
  $CMD_STRING.= " 2>&1";
  echo shell_exec($CMD_STRING);
?>
